services:
  - type: web
    name: fooddelivery-app
    env: python
    branch: main
    rootDir: fooddelivery-app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    plan: starter
